import java.io.IOException;
import student.TestCase;

// On my honor:
//
// - I have not used source code obtained from another student,
// or any other unauthorized source, either modified or
// unmodified.
//
// - All source code and documentation used in my program is
// either my original work, or was derived by me from the
// source code published in the textbook for this course.
//
// - I have not discussed coding details about this project with
// anyone other than my partner (in the case of a joint
// submission), instructor, ACM/UPE tutors or the TAs assigned
// to this course. I understand that I may discuss the concepts
// of this program with other students, and that another student
// may help me debug my program so long as neither of us writes
// anything during the discussion or modifies any computer file
// during the discussion. I have violated neither the spirit nor
// letter of this restriction.
/**
 * Test for DNAdbase
 * 
 * @author James Kim (thejameskim)
 * @author Natalie Kakish (Nataliekakish)
 * @version (2020-11-27)
 */
public class DNAdbaseTest extends TestCase {

    /**
     * Test for DNAbase
     * @throws NumberFormatException
     * @throws IOException
     */
    public void testDNAdbase() throws NumberFormatException, IOException {
        DNAdbase.main(new String[] {});

        assertEquals("SequenceID CTG not found\n" + "Sequence IDs:\n"
            + "ATAAC: hash slot [4]\n" + "Free Block List: none\n"
            + "Sequence Removed GTC:\n"
            + "CATGATGATCTTCTAGGAGGATGCGTAAACGATAAGGGTGGGATCTACTAACAC"
            + "TCCAGA\n"
            + "Sequence Removed GACC:\n"
            + "TGACGTCCCGGCACGGGGCATCTGTTCAACACCAGCATTCAACTCCTTGGTTC"
            + "TACATATCCTCCGTCCATGTAAACGAAGAC\n"
            + "Sequence Removed ATAAC:\n"
            + "TTGTGTCCCGAGTAGACCAAAAAGAGTGCCCGCTCACTCTGTTCCGCTGGAA"
            + "TGATGCAGACTTGCTGCTTACTTTATAGAACCATCTTCGA\n"
            + "SequenceID GCC not found\n" + "SequenceID TCGAC not fou"
                + "nd\n"
            + "Sequence IDs:\n" + "Free Block List: none\n"
            + "SequenceID GGAG not found\n" + "SequenceID TAGTT not fo"
                + "und\n"
            + "Sequence Removed TTC:\n"
            + "GAAATCATAGGTTGACAAGAAAGCGTATCATACGCCTCGCGGACAAGCCGGTACA"
            + "ATTAAACTCCCGCCGA\n"
            + "SequenceID TTAGA not found\n" + "SequenceID GC not found\n"
            + "Sequence Removed AAAA:\n"
            + "TCGATACAACGATCAAGTTACAGCTTGTCAACGCTCGTCGAACTAGAGGCGGTAC\n"
            + "SequenceID TCAG exists\n" + "Sequence Removed TCTGC:\n"
            + "CGTATCGCGTTGTTAGCTCATCAGGGATCCGCATTATAACACTGTCATCTGGTGC\n"
            + "Sequence Removed TTGC:\n"
            + "CGAAAGCAATGTTCTGGACATAGGTAGGCAACGCCCGTTTCTATGCCTCCCCAG"
            + "ATTCCT\n"
            + "SequenceID CACAT not found\n" + "Sequence Removed TCAG:\n"
            + "CAAGATCGACAGTCAGTATTGCCACAACATACTGAAACTGCCCGCCCGGGGCGT"
            + "TACAGACCTC\n"
            + "SequenceID AGCGT not found\n" + "SequenceID TTTT exists\n"
            + "SequenceID TACGG exists\n" + "Sequence IDs:\n"
            + "TACGG: hash slot [19]\n" + "TTTT: hash slot [27]\n"
            + "Free Block List:\n"
            + "[Block 1] Starting Byte Location: 8, Size 8 bytes\n"
            + "SequenceID TACGG exists\n" + "SequenceID TGTC not found\n"
            + "SequenceID TT not found\n" + "SequenceID AACA not found\n"
            + "Sequence Removed TTTT:\n" + "AGCACTCACACCACTAGGAGATGGC\n"
            + "Sequence Removed CGA:\n"
            + "CACAAACGGGTACATCATGGTGTGTCAGAAAGGCCCGTGATGGTGTACGGGG"
            + "GTCGCTTGCAGTCATC\n"
            + "Sequence Removed TACGG:\n" + "CCCAGTGCGCCTC\n"
            + "SequenceID CAA not found\n" + "SequenceID CAAT not found\n"
            + "Sequence IDs:\n" + "Free Block List: none\n" + "Sequence IDs:\n"
            + "AAC: hash slot [18]\n" + "Free Block List: none\n"
            + "Sequence IDs:\n" + "AAC: hash slot [18]\n"
            + "Free Block List: none\n" + "SequenceID AAA not found\n"
            + "Sequence Removed AAC:\n" + "AAATGAGTCGCACCCTTGGACTGAGTGTTAA\n"
            + "Sequence Removed TGCA:\n"
            + "CAAACTATAGGACGCAGTCCGAATGCGTGGTAACGTTGGTTGAACCTGCGAAA"
            + "CGCTGTCACAGACGCTCCAGC\n"
            + "SequenceID TGT not found\n" + "SequenceID GCCAG not found\n"
            + "SequenceID GGA not found\n" + "SequenceID TAAA not found\n"
            + "SequenceID TTAT not found\n" + "SequenceID AGCTA exists\n"
            + "Sequence IDs:\n" + "CTAC: hash slot [9]\n"
            + "GGCC: hash slot [21]\n" + "TTGAG: hash slot [22]\n"
            + "CCAAA: hash slot [28]\n" + "GCAT: hash slot [29]\n"
            + "AGCTA: hash slot [30]\n" + "GCGC: hash slot [31]\n"
            + "Free Block List: none\n" + "Sequence Removed CCAAA:\n"
            + "AATCCCGTTCTGCA\n" + "Sequence IDs:\n" + "TAT: hash slot [3]\n"
            + "CTAC: hash slot [9]\n" + "ACATA: hash slot [14]\n"
            + "G: hash slot [19]\n" + "GGCC: hash slot [21]\n"
            + "TTGAG: hash slot [22]\n" + "CCACA: hash slot [28]\n"
            + "GCAT: hash slot [29]\n" + "AGCTA: hash slot [30]\n"
            + "GCGC: hash slot [31]\n" + "Free Block List: none\n"
            + "Sequence Removed GGCC:\n"
            + "GCTGGCGCCCGCTCGCGTGGTTGACTGCCATTAACCGCACAAAAAAACTCG"
            + "TTGGACTCCGACGTTTTGCCCCCTGCGG\n"
            + "Sequence IDs:\n" + "TAT: hash slot [3]\n"
            + "CTAC: hash slot [9]\n" + "ACATA: hash slot [14]\n"
            + "G: hash slot [19]\n" + "TTGAG: hash slot [22]\n"
            + "CCACA: hash slot [28]\n" + "GCAT: hash slot [29]\n"
            + "AGCTA: hash slot [30]\n" + "GCGC: hash slot [31]\n"
            + "Free Block List:\n"
            + "[Block 1] Starting Byte Location: 0, Size 21 bytes\n"
            + "Sequence Removed GCGC:\n"
            + "GAACCACCGGTGCGGGCGTGCCGCGTAACATTGCCCGTTCGACAGACACA"
            + "AAACAATATC\n"
            + "SequenceID GCAT exists\n" + "SequenceID TG not found\n"
            + "SequenceID TTGAG exists\n" + "Sequence Removed CTAC:\n"
            + "GTTAACGCCTGCGCTAAGGGCCTGTCTTCCACACTGAGTTTAATTCTTGCTGTCT"
            + "ACCGAGAAAATCT\n"
            + "SequenceID CCAG not found\n" + "SequenceID TAT exists\n"
            + "Sequence Removed G:\n"
            + "TGCAGCCTGGAGCTGCACGCCACGCCTAGAGAATCCTTCTTCCCCTCCTCGCGGAG"
            + "GAGAGCGGAGA\n"
            + "Sequence IDs:\n" + "TAT: hash slot [3]\n"
            + "CCAA: hash slot [4]\n" + "CCT: hash slot [5]\n"
            + "CTAG: hash slot [9]\n" + "CAATA: hash slot [12]\n"
            + "ACATA: hash slot [14]\n" + "ACTTA: hash slot [15]\n"
            + "TTGAG: hash slot [22]\n" + "CCACA: hash slot [28]\n"
            + "GCAT: hash slot [29]\n" + "AGCTA: hash slot [30]\n"
            + "TCTTT: hash slot [31]\n" + "Free Block List:\n"
            + "[Block 1] Starting Byte Location: 18, Size 3 bytes\n"
            + "[Block 2] Starting Byte Location: 62, Size 16 bytes\n"
            + "Sequence Removed CCACA:\n"
            + "CCCGTTACCATTTCCAGGCTTGTGCCTTGTCTTTCTGAGG\n"
            + "Sequence Removed CAATA:\n"
            + "CGGACTGCGGACGAAGAAGAGGTAGGTAGATATCAGGTCAGCTTG\n"
            + "SequenceID ACCC not found\n" + "SequenceID ATTAG not found\n"
            + "SequenceID CCT exists\n" + "Sequence Removed AGCTA:\n"
            + "TGTTACGCCGTCACGTTTCGTTACGGACACGTGGTGTCGAACCTCATAGACATA"
            + "TACTTTGTGAGTCGAGATCGCCTGGAC\n"
            + "SequenceID ACC not found\n" + "SequenceID ACCGG not found\n"
            + "Sequence IDs:\n" + "TAT: hash slot [3]\n"
            + "CCAA: hash slot [4]\n" + "CCT: hash slot [5]\n"
            + "CTAG: hash slot [9]\n" + "ACATA: hash slot [14]\n"
            + "ACTTA: hash slot [15]\n" + "TCGC: hash slot [19]\n"
            + "TTGAG: hash slot [22]\n" + "GCAT: hash slot [29]\n"
            + "TCTTT: hash slot [31]\n" + "Free Block List:\n"
            + "[Block 1] Starting Byte Location: 10, Size 2 bytes\n"
            + "[Block 2] Starting Byte Location: 19, Size 25 bytes\n"
            + "[Block 3] Starting Byte Location: 62, Size 16 bytes\n"
            + "[Block 4] Starting Byte Location: 140, Size 3 bytes\n"
            + "[Block 5] Starting Byte Location: 162, Size 12 bytes\n"
            + "Sequence IDs:\n" + "TAT: hash slot [3]\n"
            + "CCAA: hash slot [4]\n" + "CCT: hash slot [5]\n"
            + "CTAG: hash slot [9]\n" + "ACATA: hash slot [14]\n"
            + "ACTTA: hash slot [15]\n" + "TCGC: hash slot [19]\n"
            + "TTGAG: hash slot [22]\n" + "GCAT: hash slot [29]\n"
            + "TCTTT: hash slot [31]\n" + "Free Block List:\n"
            + "[Block 1] Starting Byte Location: 10, Size 2 bytes\n"
            + "[Block 2] Starting Byte Location: 19, Size 25 bytes\n"
            + "[Block 3] Starting Byte Location: 62, Size 16 bytes\n"
            + "[Block 4] Starting Byte Location: 140, Size 3 bytes\n"
            + "[Block 5] Starting Byte Location: 162, Size 12 bytes\n"
            + "SequenceID GCAT exists\n" + "Sequence Removed TTGAG:\n"
            + "TCTCTGACCATCCCTCGCCATGATTCATGCCCCGCTATCAC\n"
            + "SequenceID CCCTT not found\n" + "Sequence Removed TCTTT:\n"
            + "TGTGCTGATCTCACCAGCAAGTTTGCACTTAACCTAATTTTCGTAGTCTTTGGTAA"
            + "TGAGGTTTTCGCAGCCTTCGAGTACGCACCAACA\n"
            + "Sequence Removed TAT:\n" + "TTCCTGGATG\n" + "Sequence IDs:\n"
            + "CCAA: hash slot [4]\n" + "CCT: hash slot [5]\n"
            + "ATGCC: hash slot [6]\n" + "GCAAC: hash slot [7]\n"
            + "CTAG: hash slot [9]\n" + "GTT: hash slot [11]\n"
            + "ACATA: hash slot [14]\n" + "ACTTA: hash slot [15]\n"
            + "TCGC: hash slot [19]\n" + "GCAT: hash slot [29]\n"
            + "GATTC: hash slot [30]\n" + "Free Block List:\n"
            + "[Block 1] Starting Byte Location: 13, Size 2 bytes\n"
            + "[Block 2] Starting Byte Location: 77, Size 14 bytes\n"
            + "[Block 3] Starting Byte Location: 109, Size 4 bytes\n"
            + "[Block 4] Starting Byte Location: 142, Size 1 bytes\n"
            + "[Block 5] Starting Byte Location: 170, Size 4 bytes\n"
            + "Sequence Removed CCAA:\n" + "ACATCGTTAACGCAGATGGTCACATT"
                + "GAGTCCG\n"
            + "Sequence Removed CCT:\n"
            + "AGCGTGAATACTTTTATACTCGGTGGAAGGAGTATTTAAACTCGCCATTAAGTCG"
            + "GAGACTGGCGCAACGCGTAGGGCGAAGGTTACAAAAACATCTCCC\n"
            + "Sequence Removed ACTTA:\n"
            + "CCTCTTAGCGAGCACGATTTGCACGGGATGCGTGACAAAGGTGTACGTCAGAGATC"
            + "TCTGTCTCGAGCCA\n"
            + "SequenceID T not found\n" + "Sequence Removed CTAG:\n"
            + "CCTCTTAGCGAGCACGATTTGCACGGGATGCGTGACAAAGGTGTACGTCAGAGAT"
            + "CTCTGTCTCGAGCCA\n"
            + "Sequence Removed TCGC:\n"
            + "GTGTACGTTTTGGCTATAATAGAGGCCCTGAGCTG\n" + "Sequence Remo"
                + "ved TA:\n"
            + "CACTCTGGGGAAAGCCAGAGGGGGCTCGCCCCACGATGTTATTATTTAGAATCTC"
            + "GCTGTTGAAATGTGATTCATCCAAAAATGACGTAAATT\n"
            + "Sequence Removed ATGCC:\n"
            + "CGGCGATTGACAAAGCTGGGACGCCATGCGGGCTACATACTTCGACAACATTCCTC"
            + "GTGGAGACACCCCCCGA\n"
            + "SequenceID GATTC exists\n" + "Sequence Removed GCCCC:\n"
            + "GAACCACCGGTGCGGGCGTGCCGCGTAACATTGCCCGTTCGACAGACACAAAACAA"
            + "TATC\n"
            + "Sequence Removed GTT:\n" + "AAGGGCTGGGTCAGTGGGCATACCCCCCG\n"
            + "Sequence Removed CAGGC:\n" + "CGGGTCGT\n"
            + "Sequence Removed GCAT:\n"
            + "CGATAGGACACTTTTCGGAAATATGTTGACCAGTCAGAACTTTAAGCGTAAATC"
            + "TGTCTACCGGGAGA\n"
            + "Sequence IDs:\n" + "GAT: hash slot [1]\n"
            + "GCGCG: hash slot [2]\n" + "CCTCT: hash slot [4]\n"
            + "GCAAC: hash slot [7]\n" + "ACATA: hash slot [14]\n"
            + "TTCTT: hash slot [15]\n" + "AATT: hash slot [19]\n"
            + "AC: hash slot [22]\n" + "CAG: hash slot [23]\n"
            + "CTAAG: hash slot [26]\n" + "CGTT: hash slot [27]\n"
            + "CCATA: hash slot [28]\n" + "GATTC: hash slot [30]\n"
            + "AG: hash slot [31]\n" + "Free Block List:\n"
            + "[Block 1] Starting Byte Location: 8, Size 4 bytes\n"
            + "[Block 2] Starting Byte Location: 15, Size 1 bytes\n"
            + "[Block 3] Starting Byte Location: 44, Size 18 bytes\n"
            + "[Block 4] Starting Byte Location: 105, Size 4 bytes\n"
            + "[Block 5] Starting Byte Location: 205, Size 9 bytes\n"
            + "Sequence Removed GAT:\n" + "ATTGAGATACGATTATATAATGCCGCCTG\n"
            + "Sequence Removed TTCTT:\n"
            + "GCGATATCGACTTTGACAAAGAAGTCTCTCCAGCGGATTAGTTATAGTCTACAACCCC"
            + "TCTATCGTTAATCGGCCCGTTCAGCGCGGAGGGAG\n"
            + "Sequence Removed CAG:\n"
            + "TGCTGTAGCGGCAAGCTTTGACGAGTGGAGCAGGATAGTGGAGAATAGCACG"
            + "TCAATGTGCCTCACATGGCA\n"
            + "Sequence Removed CCTCT:\n" + "ATCCTGTCGCGACGCTGACAAA"
                + "TATGC\n"
            + "Sequence IDs:\n" + "GCGCG: hash slot [2]\n"
            + "GCAAC: hash slot [7]\n" + "ACATA: hash slot [14]\n"
            + "TTTGC: hash slot [17]\n" + "AATT: hash slot [19]\n"
            + "TCTG: hash slot [20]\n" + "AC: hash slot [22]\n"
            + "ACCAG: hash slot [24]\n" + "CTAAG: hash slot [26]\n"
            + "CGTT: hash slot [27]\n" + "CCATA: hash slot [28]\n"
            + "GATTC: hash slot [30]\n" + "AG: hash slot [31]\n"
            + "Free Block List:\n"
            + "[Block 1] Starting Byte Location: 16, Size 3 bytes\n"
            + "[Block 2] Starting Byte Location: 44, Size 18 bytes\n"
            + "[Block 3] Starting Byte Location: 87, Size 22 bytes\n"
            + "[Block 4] Starting Byte Location: 136, Size 3 bytes\n"
            + "[Block 5] Starting Byte Location: 142, Size 1 bytes\n"
            + "[Block 6] Starting Byte Location: 205, Size 16 bytes\n"
            + "Sequence Removed AATT:\n"
            + "ATGGCGTTCAAAGGTGACCTCTACCCAGTCCGTGATGACCTAACTGCACTTGGAGT"
            + "TCAGAGATGAAGAGATTTTGTATGGCCAACGAGGAA\n"
            + "SequenceID ACATA exists\n" + "Sequence Removed CGTT:\n"
            + "TTGTTATTTTTGGAATTACTGTGAACTTTCGATGGTATAGGCTCTATGTTCAGAA"
            + "GTTTCATGTGCACCAGATC\n"
            + "Sequence Removed CTAAG:\n"
            + "ATAATAGAAACTTAGTTAGCCGGCGTATCCTGAACGAAGGTCATCCGTAGTGCAT"
            + "TGTCAGACTTCGCCCAGGCCAG\n"
            + "Sequence IDs:\n" + "GAGAC: hash slot [0]\n"
            + "GCGCG: hash slot [2]\n" + "GCAAC: hash slot [7]\n"
            + "ACATA: hash slot [14]\n" + "TTTGC: hash slot [17]\n"
            + "TCTG: hash slot [20]\n" + "AC: hash slot [22]\n"
            + "ACCAG: hash slot [24]\n" + "CCATA: hash slot [28]\n"
            + "GATTC: hash slot [30]\n" + "AG: hash slot [31]\n"
            + "Free Block List:\n"
            + "[Block 1] Starting Byte Location: 16, Size 22 bytes\n"
            + "[Block 2] Starting Byte Location: 43, Size 19 bytes\n"
            + "[Block 3] Starting Byte Location: 87, Size 22 bytes\n"
            + "[Block 4] Starting Byte Location: 111, Size 2 bytes\n"
            + "[Block 5] Starting Byte Location: 138, Size 2 bytes\n"
            + "[Block 6] Starting Byte Location: 142, Size 1 bytes\n"
            + "[Block 7] Starting Byte Location: 162, Size 43 bytes\n"
            + "[Block 8] Starting Byte Location: 208, Size 13 bytes\n"
            + "SequenceID CGT not found\n" + "SequenceID GTG not found\n"
            + "Sequence Removed AC:\n"
            + "GGGATAACCATAATCCGAACCGACTACTGATGTCACCCTTTTTGACCGTTACC"
            + "TAAGCGTGATGTCCCAACCATTC\n"
            + "Sequence Removed TCTG:\n" + "AAATGAGTCGCACCCTTGGACTG"
                + "AGTGTTAA\n"
            + "Sequence Removed TTTGC:\n"
            + "TCATCCGAGTAGAGAATTTAATCTGTATATTCGCAATATAACAGGGAAGAGTGT"
            + "TACCCAATTCTATACGGAGCTTTCGCGTGCGTTAAG\n"
            + "Sequence Removed GAGAC:\n" + "AGAACCTCAC\n"
            + "Sequence Removed CTACC:\n"
            + "TGCCTTTGTGTAACATGGTGCATAATTATAAATTCAAACACCTCTGAGACTCAA"
            + "CAAGCGCG\n"
            + "Sequence Removed GGCGA:\n"
            + "CACTCTGGGGAAAGCCAGAGGGGGCTCGCCCCACGATGTTATTATTTAGAATCTC"
            + "GCTGTTGAAATGTGATTCATCCAAAAATGACGTAAATT\n"
            + "SequenceID AGTCG exists\n" + "Sequence Removed GTAG:\n"
            + "TAATT\n" + "SequenceID CTTA exists\n"
            + "Sequence Removed TGGGT:\n"
            + "AGCGGACATGCAGTATCAATTAGATGGACCCTCTAAGTTGTTTGTGTCTTACTCGT"
            + "GCTTTGTTCGGGATAGTCCAAATTAGTGTTCATCG\n"
            + "SequenceID TCGA not found\n" + "Sequence Removed CGAC:\n"
            + "ATTTA\n" + "SequenceID ACG not found\n" + "Sequence IDs:\n"
            + "GCGCG: hash slot [2]\n" + "GCAAC: hash slot [7]\n"
            + "CTTA: hash slot [9]\n" + "ACATA: hash slot [14]\n"
            + "TGGC: hash slot [19]\n" + "GGGA: hash slot [21]\n"
            + "ACCAG: hash slot [24]\n" + "AGTCG: hash slot [26]\n"
            + "CCATA: hash slot [28]\n" + "TTA: hash slot [29]\n"
            + "GATTC: hash slot [30]\n" + "AG: hash slot [31]\n"
            + "Free Block List:\n"
            + "[Block 1] Starting Byte Location: 8, Size 2 bytes\n"
            + "[Block 2] Starting Byte Location: 13, Size 1 bytes\n"
            + "[Block 3] Starting Byte Location: 32, Size 2 bytes\n"
            + "[Block 4] Starting Byte Location: 54, Size 7 bytes\n"
            + "[Block 5] Starting Byte Location: 79, Size 30 bytes\n"
            + "[Block 6] Starting Byte Location: 136, Size 2 bytes\n"
            + "[Block 7] Starting Byte Location: 162, Size 46 bytes\n"
            + "[Block 8] Starting Byte Location: 236, Size 4 bytes\n"
            + "Sequence Removed GATTC:\n" + "GCTGTCCTGG\n"
            + "Sequence Removed GCAAC:\n"
            + "CACGGCCTAGGTCAAACATCTGCTCGGCGACCCGAATAGGCACGGCGGGACCGTGTATTG\n"
            + "Sequence IDs:\n" + "GCGCG: hash slot [2]\n"
            + "CCTAG: hash slot [6]\n" + "CTTA: hash slot [9]\n"
            + "ACATA: hash slot [14]\n" + "TGGC: hash slot [19]\n"
            + "GGGA: hash slot [21]\n" + "ACCAG: hash slot [24]\n"
            + "AGTCG: hash slot [26]\n" + "CCATA: hash slot [28]\n"
            + "TTA: hash slot [29]\n" + "AG: hash slot [31]\n"
            + "Free Block List:\n"
            + "[Block 1] Starting Byte Location: 13, Size 1 bytes\n"
            + "[Block 2] Starting Byte Location: 32, Size 2 bytes\n"
            + "[Block 3] Starting Byte Location: 38, Size 5 bytes\n"
            + "[Block 4] Starting Byte Location: 54, Size 7 bytes\n"
            + "[Block 5] Starting Byte Location: 62, Size 15 bytes\n"
            + "[Block 6] Starting Byte Location: 87, Size 22 bytes\n"
            + "[Block 7] Starting Byte Location: 136, Size 2 bytes\n"
            + "[Block 8] Starting Byte Location: 140, Size 2 bytes\n"
            + "[Block 9] Starting Byte Location: 162, Size 46 bytes\n"
            + "[Block 10] Starting Byte Location: 236, Size 4 bytes\n"
            + "Sequence Removed GGGA:\n" + "ATATGGGTTTCTTGA\n"
            + "Sequence IDs:\n" + "GCGCG: hash slot [2]\n"
            + "CCTAG: hash slot [6]\n" + "CTTA: hash slot [9]\n"
            + "ACATA: hash slot [14]\n" + "TGGC: hash slot [19]\n"
            + "ACCAG: hash slot [24]\n" + "AGTCG: hash slot [26]\n"
            + "CGAGC: hash slot [27]\n" + "CCATA: hash slot [28]\n"
            + "TTA: hash slot [29]\n" + "AG: hash slot [31]\n"
            + "Free Block List:\n"
            + "[Block 1] Starting Byte Location: 13, Size 1 bytes\n"
            + "[Block 2] Starting Byte Location: 32, Size 11 bytes\n"
            + "[Block 3] Starting Byte Location: 54, Size 7 bytes\n"
            + "[Block 4] Starting Byte Location: 62, Size 15 bytes\n"
            + "[Block 5] Starting Byte Location: 106, Size 3 bytes\n"
            + "[Block 6] Starting Byte Location: 112, Size 1 bytes\n"
            + "[Block 7] Starting Byte Location: 140, Size 2 bytes\n"
            + "[Block 8] Starting Byte Location: 162, Size 46 bytes\n"
            + "[Block 9] Starting Byte Location: 236, Size 4 bytes\n"
            + "Sequence IDs:\n" + "GCGCG: hash slot [2]\n"
            + "CCTAG: hash slot [6]\n" + "CTTA: hash slot [9]\n"
            + "ACATA: hash slot [14]\n" + "AAG: hash slot [18]\n"
            + "TGGC: hash slot [19]\n" + "ACCT: hash slot [22]\n"
            + "ACCAG: hash slot [24]\n" + "AGTCG: hash slot [26]\n"
            + "CGAGC: hash slot [27]\n" + "CCATA: hash slot [28]\n"
            + "TTA: hash slot [29]\n" + "AG: hash slot [31]\n"
            + "Free Block List:\n"
            + "[Block 1] Starting Byte Location: 32, Size 11 bytes\n"
            + "[Block 2] Starting Byte Location: 54, Size 7 bytes\n"
            + "[Block 3] Starting Byte Location: 62, Size 15 bytes\n"
            + "[Block 4] Starting Byte Location: 106, Size 3 bytes\n"
            + "[Block 5] Starting Byte Location: 179, Size 29 bytes\n"
            + "[Block 6] Starting Byte Location: 236, Size 4 bytes\n"
            + "SequenceID CTAA not found\n" + "Sequence Removed CCTAG:\n"
            + "CCACACGTATCTGTTTCACTCGACGCTGAT\n" + "Sequence IDs:\n"
            + "GCGCG: hash slot [2]\n" + "CTTA: hash slot [9]\n"
            + "ACATA: hash slot [14]\n" + "AAG: hash slot [18]\n"
            + "TGGC: hash slot [19]\n" + "ACCT: hash slot [22]\n"
            + "ACCAG: hash slot [24]\n" + "AGTCG: hash slot [26]\n"
            + "CGAGC: hash slot [27]\n" + "CCATA: hash slot [28]\n"
            + "TTA: hash slot [29]\n" + "AG: hash slot [31]\n"
            + "Free Block List:\n"
            + "[Block 1] Starting Byte Location: 8, Size 2 bytes\n"
            + "[Block 2] Starting Byte Location: 32, Size 11 bytes\n"
            + "[Block 3] Starting Byte Location: 54, Size 7 bytes\n"
            + "[Block 4] Starting Byte Location: 62, Size 15 bytes\n"
            + "[Block 5] Starting Byte Location: 79, Size 8 bytes\n"
            + "[Block 6] Starting Byte Location: 106, Size 3 bytes\n"
            + "[Block 7] Starting Byte Location: 179, Size 29 bytes\n"
            + "[Block 8] Starting Byte Location: 236, Size 4 bytes\n"
            + "Sequence IDs:\n" + "GCGCG: hash slot [2]\n"
            + "CC: hash slot [3]\n" + "CTTA: hash slot [9]\n"
            + "ACATA: hash slot [14]\n" + "AAG: hash slot [18]\n"
            + "TGGC: hash slot [19]\n" + "ACCT: hash slot [22]\n"
            + "ACCAG: hash slot [24]\n" + "AGTCG: hash slot [26]\n"
            + "CGAGC: hash slot [27]\n" + "CCATA: hash slot [28]\n"
            + "TTA: hash slot [29]\n" + "AG: hash slot [31]\n"
            + "Free Block List:\n"
            + "[Block 1] Starting Byte Location: 9, Size 1 bytes\n"
            + "[Block 2] Starting Byte Location: 32, Size 11 bytes\n"
            + "[Block 3] Starting Byte Location: 54, Size 7 bytes\n"
            + "[Block 4] Starting Byte Location: 62, Size 15 bytes\n"
            + "[Block 5] Starting Byte Location: 79, Size 8 bytes\n"
            + "[Block 6] Starting Byte Location: 106, Size 3 bytes\n"
            + "[Block 7] Starting Byte Location: 195, Size 13 bytes\n"
            + "[Block 8] Starting Byte Location: 236, Size 4 bytes\n"
            + "SequenceID GCGCG exists\n" + "Sequence Removed CGAGC:\n"
            + "TTGTTATTTTTGGAATTACTGTGAACTTTCGATGGTATAGGCTCTATGTTCAGAAG"
            + "TTTCATGTGCACCAGATC\n"
            + "Sequence Removed ACCT:\n" + "AAAGT\n" + "SequenceID AAG exists\n"
            + "Sequence Removed CC:\n"
            + "CCTGGTAAATTGAAATGGCAGAGCGTGTATAAGAATCTTAATGCAATGAATACCC"
            + "TTAGGAGT\n"
            + "SequenceID GAA exists\n" + "SequenceID ACATA exists\n"
            + "SequenceID CG not found\n" + "Sequence Removed GGG:\n"
            + "CTAGAAAGCAGCCCTTGATAGTTA\n" + "Sequence Removed AG:\n"
            + "GGATGCATCGCCACCTCTGACCTTACGACGCGCTGTCGTGGGATGGTGGACATGA"
            + "AGTCTGGCCGTCGCTGTACCGGAGCTGATCGAGCGCAACAGATC\n"
            + "Sequence IDs:\n" + "ATCTT: hash slot [0]\n"
            + "GAA: hash slot [1]\n" + "GCGCG: hash slot [2]\n"
            + "CTTA: hash slot [9]\n" + "ACATA: hash slot [14]\n"
            + "AAG: hash slot [18]\n" + "TGGC: hash slot [19]\n"
            + "ACCAG: hash slot [24]\n" + "AGTCG: hash slot [26]\n"
            + "CCATA: hash slot [28]\n" + "TTA: hash slot [29]\n"
            + "AGA: hash slot [30]\n" + "Free Block List:\n"
            + "[Block 1] Starting Byte Location: 8, Size 1 bytes\n"
            + "[Block 2] Starting Byte Location: 13, Size 2 bytes\n"
            + "[Block 3] Starting Byte Location: 54, Size 7 bytes\n"
            + "[Block 4] Starting Byte Location: 62, Size 15 bytes\n"
            + "[Block 5] Starting Byte Location: 96, Size 10 bytes\n"
            + "[Block 6] Starting Byte Location: 136, Size 2 bytes\n"
            + "[Block 7] Starting Byte Location: 140, Size 2 bytes\n"
            + "[Block 8] Starting Byte Location: 179, Size 16 bytes\n"
            + "Sequence Removed ATCTT:\n"
            + "TCTTTCGACCCGATAAAAGTCGAGGTATTCCGTAGTCGCTTCACCA"
            + "AATTTAGATCCGTTCCATACG\n"
            + "SequenceID TATC not found\n" + "SequenceID AGTCG exists\n"
            + "Sequence Removed CTTA:\n"
            + "GCCAAATGTATGGTTGCTAGCGAAGACCAGGGCTTACAACCATTGTACAAA\n"
            + "Sequence Removed TGGC:\n"
            + "TCTCTGACCATCCCTCGCCATGATTCATGCCCCGCTATCAC\n"
            + "SequenceID TTA exists\n" + "SequenceID CGAGA not found\n"
            + "Sequence Removed AAG:\n"
            + "TGCAGCCTGGAGCTGCACGCCACGCCTAGAGAATCCTTCTTCCCCTCCTCG"
            + "CGGAGGAGAGCGGAGA\n"
            + "Sequence IDs:\n" + "ACAAC: hash slot [0]\n"
            + "GAA: hash slot [1]\n" + "GCGCG: hash slot [2]\n"
            + "TAG: hash slot [3]\n" + "GAGG: hash slot [4]\n"
            + "ACATA: hash slot [14]\n" + "TTACC: hash slot [17]\n"
            + "GGTC: hash slot [21]\n" + "ACCAG: hash slot [24]\n"
            + "AGTCG: hash slot [26]\n" + "CCATA: hash slot [28]\n"
            + "TTA: hash slot [29]\n" + "AGA: hash slot [30]\n"
            + "AGCG: hash slot [31]\n" + "Free Block List:\n"
            + "[Block 1] Starting Byte Location: 51, Size 11 bytes\n"
            + "[Block 2] Starting Byte Location: 97, Size 9 bytes\n"
            + "[Block 3] Starting Byte Location: 112, Size 1 bytes\n"
            + "[Block 4] Starting Byte Location: 140, Size 3 bytes\n"
            + "[Block 5] Starting Byte Location: 162, Size 17 bytes\n"
            + "[Block 6] Starting Byte Location: 192, Size 3 bytes\n"
            + "[Block 7] Starting Byte Location: 216, Size 5 bytes\n"
            + "Sequence Removed AGA:\n"
            + "TCTCTGACCATCCCTCGCCATGATTCATGCCCCGCTATCAC\n"
            + "Sequence Removed AGCG:\n" + "TTAAGAGTAAATTGGGCATCCAGTTACGTT\n"
            + "Sequence Removed GGTC:\n"
            + "GCTAACAGGCGAAGCTGACTCGCTCTGTGGCAAAATGACTTGTCTTCACCAT\n"
            + "SequenceID TAC not found\n" + "Sequence IDs:\n"
            + "ACAAC: hash slot [0]\n" + "GAA: hash slot [1]\n"
            + "GCGCG: hash slot [2]\n" + "TAG: hash slot [3]\n"
            + "GAGG: hash slot [4]\n" + "TAGTC: hash slot [7]\n"
            + "ACATA: hash slot [14]\n" + "TTACC: hash slot [17]\n"
            + "ACCAG: hash slot [24]\n" + "AGTCG: hash slot [26]\n"
            + "CGAT: hash slot [27]\n" + "CCATA: hash slot [28]\n"
            + "TTA: hash slot [29]\n" + "Free Block List:\n"
            + "[Block 1] Starting Byte Location: 8, Size 1 bytes\n"
            + "[Block 2] Starting Byte Location: 13, Size 1 bytes\n"
            + "[Block 3] Starting Byte Location: 42, Size 1 bytes\n"
            + "[Block 4] Starting Byte Location: 51, Size 19 bytes\n"
            + "[Block 5] Starting Byte Location: 140, Size 3 bytes\n"
            + "[Block 6] Starting Byte Location: 162, Size 33 bytes\n"
            + "[Block 7] Starting Byte Location: 216, Size 5 bytes\n"
            + "SequenceID GAGG exists\n" + "SequenceID CTCCA not found\n"
            + "SequenceID TACAC not found\n" + "Sequence Removed TAGTC:\n"
            + "GCGTCGAGAGAAGCATGTAAGTATCGAGTGTTCGTGGG\n"
            + "Sequence Removed GACG:\n"
            + "GTAGACCTGTCACAGAGGTAGGCCTTAAGCGAATCGCTATACTCGCGACCGTGGA"
            + "CTTCTGACAGGATTTATTA\n"
            + "Sequence IDs:\n" + "ACAAC: hash slot [0]\n"
            + "GAA: hash slot [1]\n" + "GCGCG: hash slot [2]\n"
            + "TAG: hash slot [3]\n" + "GAGG: hash slot [4]\n"
            + "ACATA: hash slot [14]\n" + "TTACC: hash slot [17]\n"
            + "ACCAG: hash slot [24]\n" + "ATTG: hash slot [25]\n"
            + "AGTCG: hash slot [26]\n" + "CGAT: hash slot [27]\n"
            + "CCATA: hash slot [28]\n" + "TTA: hash slot [29]\n"
            + "ATA: hash slot [30]\n" + "TTACA: hash slot [31]\n"
            + "Free Block List:\n"
            + "[Block 1] Starting Byte Location: 8, Size 1 bytes\n"
            + "[Block 2] Starting Byte Location: 32, Size 10 bytes\n"
            + "[Block 3] Starting Byte Location: 51, Size 19 bytes\n"
            + "[Block 4] Starting Byte Location: 140, Size 3 bytes\n"
            + "[Block 5] Starting Byte Location: 184, Size 11 bytes\n"
            + "[Block 6] Starting Byte Location: 216, Size 5 bytes\n"
            + "Sequence IDs:\n" + "ACAAC: hash slot [0]\n"
            + "GAA: hash slot [1]\n" + "GCGCG: hash slot [2]\n"
            + "TAG: hash slot [3]\n" + "GAGG: hash slot [4]\n"
            + "CTT: hash slot [9]\n" + "ACATA: hash slot [14]\n"
            + "TTACC: hash slot [17]\n" + "ACCAG: hash slot [24]\n"
            + "ATTG: hash slot [25]\n" + "AGTCG: hash slot [26]\n"
            + "CGAT: hash slot [27]\n" + "CCATA: hash slot [28]\n"
            + "TTA: hash slot [29]\n" + "ATA: hash slot [30]\n"
            + "TTACA: hash slot [31]\n" + "Free Block List:\n"
            + "[Block 1] Starting Byte Location: 51, Size 19 bytes\n"
            + "[Block 2] Starting Byte Location: 140, Size 3 bytes\n"
            + "[Block 3] Starting Byte Location: 184, Size 11 bytes\n"
            + "[Block 4] Starting Byte Location: 216, Size 5 bytes\n"
            + "SequenceID TTACA exists\n" + "SequenceID GGAAT not found\n"
            + "Sequence Removed CTT:\n"
            + "GATGCGGTGCCCCATAAAGATGGATTTTTCACGGGATAC\n" + "Sequence IDs:\n"
            + "ACAAC: hash slot [0]\n" + "GAA: hash slot [1]\n"
            + "GCGCG: hash slot [2]\n" + "TAG: hash slot [3]\n"
            + "GAGG: hash slot [4]\n" + "AGTC: hash slot [5]\n"
            + "GCG: hash slot [6]\n" + "ACATA: hash slot [14]\n"
            + "TTACC: hash slot [17]\n" + "C: hash slot [18]\n"
            + "ACCAG: hash slot [24]\n" + "ATTG: hash slot [25]\n"
            + "AGTCG: hash slot [26]\n" + "CGAT: hash slot [27]\n"
            + "CCATA: hash slot [28]\n" + "TTA: hash slot [29]\n"
            + "ATA: hash slot [30]\n" + "TTACA: hash slot [31]\n"
            + "Free Block List:\n"
            + "[Block 1] Starting Byte Location: 41, Size 1 bytes\n"
            + "[Block 2] Starting Byte Location: 51, Size 19 bytes\n"
            + "[Block 3] Starting Byte Location: 141, Size 2 bytes\n"
            + "[Block 4] Starting Byte Location: 192, Size 3 bytes\n"
            + "[Block 5] Starting Byte Location: 216, Size 5 bytes\n"
            + "Sequence Removed AGTC:\n"
            + "TGTGTCGCGCTCCTCATATCGCATGGACACACCCGTGAAGGCACTATCTGGCGTCCAGT"
            + "AGTACACCCACTGAGTATCTTACTAGCCCCGCGC\n"
            + "Sequence Removed C:\n" + "GGGGTATTATTATCTTCAACCCCGCGGTGCGG\n"
            + "Sequence Removed CCATA:\n" + "CAACCAGACATTACAGAAAAGTCCTCTCT\n"
            + "Sequence IDs:\n" + "ACAAC: hash slot [0]\n"
            + "GAA: hash slot [1]\n" + "GCGCG: hash slot [2]\n"
            + "TAG: hash slot [3]\n" + "GAGG: hash slot [4]\n"
            + "GCG: hash slot [6]\n" + "ACATA: hash slot [14]\n"
            + "TTACC: hash slot [17]\n" + "ACCAG: hash slot [24]\n"
            + "ATTG: hash slot [25]\n" + "AGTCG: hash slot [26]\n"
            + "CGAT: hash slot [27]\n" + "TTA: hash slot [29]\n"
            + "ATA: hash slot [30]\n" + "TTACA: hash slot [31]\n"
            + "Free Block List:\n"
            + "[Block 1] Starting Byte Location: 0, Size 9 bytes\n"
            + "[Block 2] Starting Byte Location: 32, Size 8 bytes\n"
            + "[Block 3] Starting Byte Location: 41, Size 1 bytes\n"
            + "[Block 4] Starting Byte Location: 51, Size 19 bytes\n"
            + "[Block 5] Starting Byte Location: 109, Size 2 bytes\n"
            + "[Block 6] Starting Byte Location: 140, Size 3 bytes\n"
            + "[Block 7] Starting Byte Location: 192, Size 3 bytes\n"
            + "[Block 8] Starting Byte Location: 216, Size 5 bytes\n"
            + "Sequence Removed GCGCG:\n" + "CTT\n"
            + "Sequence Removed AATGA:\n"
            + "ACTGCCTAGATTGGCCCTCTAATGCGATTTTCCTCAGCCGGTGCCTCGCTACGTTAG"
            + "CACGCCTGGTCTTGTTCCATT\n"
            + "SequenceID GTTCT not found\n" + "Sequence IDs:\n"
            + "ACAAC: hash slot [0]\n" + "GAA: hash slot [1]\n"
            + "TAG: hash slot [3]\n" + "GAGG: hash slot [4]\n"
            + "AGG: hash slot [5]\n" + "GCG: hash slot [6]\n"
            + "CCTT: hash slot [7]\n" + "ACATA: hash slot [14]\n"
            + "TTACC: hash slot [17]\n" + "ACCAG: hash slot [24]\n"
            + "ATTG: hash slot [25]\n" + "AGTCG: hash slot [26]\n"
            + "CGAT: hash slot [27]\n" + "CGCG: hash slot [28]\n"
            + "TTA: hash slot [29]\n" + "ATA: hash slot [30]\n"
            + "TTACA: hash slot [31]\n" + "Free Block List:\n"
            + "[Block 1] Starting Byte Location: 0, Size 9 bytes\n"
            + "[Block 2] Starting Byte Location: 32, Size 8 bytes\n"
            + "[Block 3] Starting Byte Location: 63, Size 7 bytes\n"
            + "[Block 4] Starting Byte Location: 78, Size 1 bytes\n"
            + "[Block 5] Starting Byte Location: 109, Size 2 bytes\n"
            + "[Block 6] Starting Byte Location: 140, Size 3 bytes\n"
            + "[Block 7] Starting Byte Location: 192, Size 3 bytes\n"
            + "SequenceID GAGG exists\n" + "Sequence Removed CTGCG:\n"
            + "AGGACATC\n" + "SequenceID AGGC not found\n"
            + "Sequence Removed GAC:\n"
            + "GGGCCCGGGCGTGAACTCACGTGGGTTGTACGGTTTTGTGTTCCTGAGCTCGCCTTC"
            + "AGGTTCTAAATGTGAGAGATTTGG\n"
            + "SequenceID TCGT not found\n" + "Sequence Removed GCG:\n"
            + "CTCCACATTAACTATGGTCGGGGAGTCCG\n" + "Sequence Removed CGCG:\n"
            + "CAACCCATGATCTTCGATCTAGTGAATGAAATGTCTCAGACCAATACGCGGTATGCCA"
            + "GCCAATGGAATGGAACACAAT\n"
            + "SequenceID AATTA not found\n" + "Sequence IDs:\n"
            + "ACAAC: hash slot [0]\n" + "GAA: hash slot [1]\n"
            + "GGTGT: hash slot [2]\n" + "TAG: hash slot [3]\n"
            + "GAGG: hash slot [4]\n" + "AGG: hash slot [5]\n"
            + "CCTT: hash slot [7]\n" + "CCCA: hash slot [8]\n"
            + "TACGC: hash slot [9]\n" + "CAC: hash slot [10]\n"
            + "GTGC: hash slot [11]\n" + "CACTA: hash slot [12]\n"
            + "CCCT: hash slot [13]\n" + "ACATA: hash slot [14]\n"
            + "TTACC: hash slot [17]\n" + "AA: hash slot [18]\n"
            + "TC: hash slot [19]\n" + "TGTT: hash slot [20]\n"
            + "GGTT: hash slot [21]\n" + "CGATG: hash slot [22]\n"
            + "CATA: hash slot [23]\n" + "ACCAG: hash slot [24]\n"
            + "ATTG: hash slot [25]\n" + "AGTCG: hash slot [26]\n"
            + "CGAT: hash slot [27]\n" + "AAAT: hash slot [28]\n"
            + "TTA: hash slot [29]\n" + "ATA: hash slot [30]\n"
            + "TTACA: hash slot [31]\n" + "Free Block List:\n"
            + "[Block 1] Starting Byte Location: 141, Size 1 bytes\n"
            + "[Block 2] Starting Byte Location: 184, Size 8 bytes\n"
            + "[Block 3] Starting Byte Location: 261, Size 20 bytes\n"
            + "[Block 4] Starting Byte Location: 437, Size 11 bytes\n"
            + "SequenceID CACTA exists\n" + "Sequence IDs:\n"
            + "ACAAC: hash slot [0]\n" + "GAA: hash slot [1]\n"
            + "GGTGT: hash slot [2]\n" + "TAG: hash slot [3]\n"
            + "GAGG: hash slot [4]\n" + "AGG: hash slot [5]\n"
            + "AT: hash slot [6]\n" + "CCTT: hash slot [7]\n"
            + "CCCA: hash slot [8]\n" + "TACGC: hash slot [9]\n"
            + "CAC: hash slot [10]\n" + "GTGC: hash slot [11]\n"
            + "CACTA: hash slot [12]\n" + "CCCT: hash slot [13]\n"
            + "ACATA: hash slot [14]\n" + "TCAAC: hash slot [15]\n"
            + "TTACC: hash slot [17]\n" + "AA: hash slot [18]\n"
            + "TC: hash slot [19]\n" + "TGTT: hash slot [20]\n"
            + "GGTT: hash slot [21]\n" + "CGATG: hash slot [22]\n"
            + "CATA: hash slot [23]\n" + "ACCAG: hash slot [24]\n"
            + "ATTG: hash slot [25]\n" + "AGTCG: hash slot [26]\n"
            + "CGAT: hash slot [27]\n" + "AAAT: hash slot [28]\n"
            + "TTA: hash slot [29]\n" + "ATA: hash slot [30]\n"
            + "TTACA: hash slot [31]\n" + "Free Block List:\n"
            + "[Block 1] Starting Byte Location: 186, Size 6 bytes\n"
            + "[Block 2] Starting Byte Location: 273, Size 8 bytes\n"
            + "[Block 3] Starting Byte Location: 437, Size 11 bytes\n"
            + "SequenceID ACT not found\n" + "SequenceID TC exists\n"
            + "SequenceID TTACA exists\n"
            + "Bucket full. Sequence TCGCA could not be inserted\n"
            + "Bucket full. Sequence TTTC could not be inserted\n"
            + "Bucket full. Sequence TCCT could not be inserted\n"
            + "Bucket full. Sequence GG could not be inserted\n"
            + "Bucket full. Sequence TCG could not be inserted\n"
            + "Bucket full. Sequence CCA could not be inserted\n"
            + "Bucket full. Sequence GCT could not be inserted\n"
            + "Bucket full. Sequence TTTG could not be inserted\n"
            + "Bucket full. Sequence CCGG could not be inserted\n"
            + "Bucket full. Sequence AGATG could not be inserted\n"
            + "Sequence IDs:\n" + "ACAAC: hash slot [0]\n"
            + "GAA: hash slot [1]\n" + "GGTGT: hash slot [2]\n"
            + "TAG: hash slot [3]\n" + "GAGG: hash slot [4]\n"
            + "AGG: hash slot [5]\n" + "AT: hash slot [6]\n"
            + "CCTT: hash slot [7]\n" + "CCCA: hash slot [8]\n"
            + "TACGC: hash slot [9]\n" + "CAC: hash slot [10]\n"
            + "GTGC: hash slot [11]\n" + "CACTA: hash slot [12]\n"
            + "CCCT: hash slot [13]\n" + "ACATA: hash slot [14]\n"
            + "TCAAC: hash slot [15]\n" + "GT: hash slot [16]\n"
            + "TTACC: hash slot [17]\n" + "AA: hash slot [18]\n"
            + "TC: hash slot [19]\n" + "TGTT: hash slot [20]\n"
            + "GGTT: hash slot [21]\n" + "CGATG: hash slot [22]\n"
            + "CATA: hash slot [23]\n" + "ACCAG: hash slot [24]\n"
            + "ATTG: hash slot [25]\n" + "AGTCG: hash slot [26]\n"
            + "CGAT: hash slot [27]\n" + "AAAT: hash slot [28]\n"
            + "TTA: hash slot [29]\n" + "ATA: hash slot [30]\n"
            + "TTACA: hash slot [31]\n" + "Free Block List:\n"
            + "[Block 1] Starting Byte Location: 187, Size 5 bytes\n"
            + "[Block 2] Starting Byte Location: 273, Size 8 bytes\n"
            + "[Block 3] Starting Byte Location: 437, Size 11 bytes\n"
            + "Bucket full. Sequence ATT could not be inserted\n"
            + "Bucket full. Sequence GAGAA could not be inserted\n"
            + "Bucket full. Sequence CGTTT could not be inserted\n"
            + "Bucket full. Sequence TCT could not be inserted\n"
            + "Bucket full. Sequence GAATC could not be inserted\n"
            + "Sequence IDs:\n" + "ACAAC: hash slot [0]\n"
            + "GAA: hash slot [1]\n" + "GGTGT: hash slot [2]\n"
            + "TAG: hash slot [3]\n" + "GAGG: hash slot [4]\n"
            + "AGG: hash slot [5]\n" + "AT: hash slot [6]\n"
            + "CCTT: hash slot [7]\n" + "CCCA: hash slot [8]\n"
            + "TACGC: hash slot [9]\n" + "CAC: hash slot [10]\n"
            + "GTGC: hash slot [11]\n" + "CACTA: hash slot [12]\n"
            + "CCCT: hash slot [13]\n" + "ACATA: hash slot [14]\n"
            + "TCAAC: hash slot [15]\n" + "GT: hash slot [16]\n"
            + "TTACC: hash slot [17]\n" + "AA: hash slot [18]\n"
            + "TC: hash slot [19]\n" + "TGTT: hash slot [20]\n"
            + "GGTT: hash slot [21]\n" + "CGATG: hash slot [22]\n"
            + "CATA: hash slot [23]\n" + "ACCAG: hash slot [24]\n"
            + "ATTG: hash slot [25]\n" + "AGTCG: hash slot [26]\n"
            + "CGAT: hash slot [27]\n" + "AAAT: hash slot [28]\n"
            + "TTA: hash slot [29]\n" + "ATA: hash slot [30]\n"
            + "TTACA: hash slot [31]\n" + "Free Block List:\n"
            + "[Block 1] Starting Byte Location: 187, Size 5 bytes\n"
            + "[Block 2] Starting Byte Location: 273, Size 8 bytes\n"
            + "[Block 3] Starting Byte Location: 437, Size 11 bytes\n"
            + "Bucket full. Sequence GAG could not be inserted\n"
            + "Bucket full. Sequence ATGT could not be inserted\n"
            + "Bucket full. Sequence TTTAC could not be inserted\n"
            + "Bucket full. Sequence TCCG could not be inserted\n"
            + "Bucket full. Sequence TCCGA could not be inserted\n"
            + "Bucket full. Sequence CCGT could not be inserted\n"
            + "Bucket full. Sequence CTGCC could not be inserted\n"
            + "Bucket full. Sequence GACAA could not be inserted\n"
            + "Bucket full. Sequence CCAGC could not be inserted\n"
            + "Bucket full. Sequence TATA could not be inserted\n"
            + "Bucket full. Sequence TCC could not be inserted\n"
            + "Bucket full. Sequence TCG could not be inserted\n"
            + "Bucket full. Sequence GCTGC could not be inserted\n"
            + "Bucket full. Sequence CTACG could not be inserted\n"
            + "Bucket full. Sequence CACT could not be inserted\n"
            + "Sequence IDs:\n" + "ACAAC: hash slot [0]\n"
            + "GAA: hash slot [1]\n" + "GGTGT: hash slot [2]\n"
            + "TAG: hash slot [3]\n" + "GAGG: hash slot [4]\n"
            + "AGG: hash slot [5]\n" + "AT: hash slot [6]\n"
            + "CCTT: hash slot [7]\n" + "CCCA: hash slot [8]\n"
            + "TACGC: hash slot [9]\n" + "CAC: hash slot [10]\n"
            + "GTGC: hash slot [11]\n" + "CACTA: hash slot [12]\n"
            + "CCCT: hash slot [13]\n" + "ACATA: hash slot [14]\n"
            + "TCAAC: hash slot [15]\n" + "GT: hash slot [16]\n"
            + "TTACC: hash slot [17]\n" + "AA: hash slot [18]\n"
            + "TC: hash slot [19]\n" + "TGTT: hash slot [20]\n"
            + "GGTT: hash slot [21]\n" + "CGATG: hash slot [22]\n"
            + "CATA: hash slot [23]\n" + "ACCAG: hash slot [24]\n"
            + "ATTG: hash slot [25]\n" + "AGTCG: hash slot [26]\n"
            + "CGAT: hash slot [27]\n" + "AAAT: hash slot [28]\n"
            + "TTA: hash slot [29]\n" + "ATA: hash slot [30]\n"
            + "TTACA: hash slot [31]\n" + "Free Block List:\n"
            + "[Block 1] Starting Byte Location: 187, Size 5 bytes\n"
            + "[Block 2] Starting Byte Location: 273, Size 8 bytes\n"
            + "[Block 3] Starting Byte Location: 437, Size 11 bytes\n" + "",
            systemOut().getHistory());
    }
}
